//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidApplicationAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentsLog
    {
        public int AppointmentID { get; set; }
        public string NameOfPet { get; set; }
        public string PrimaryPhone { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public decimal ApptTimeTotal { get; set; }
        public byte[] Comments { get; set; }
    }
}
