//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidApplicationAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContact
    {
        public int CustomerID { get; set; }
        public string NameOfPet { get; set; }
        public string PrimaryFname { get; set; }
        public string PrimaryLname { get; set; }
        public string PrimaryPhone { get; set; }
        public string PrimaryEmail { get; set; }
        public string PrimaryAddress { get; set; }
        public string PrimaryAlternateInfo { get; set; }
        public string SecondaryContactInfo { get; set; }
        public string VetInfo { get; set; }
    }
}
