//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidApplicationAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetCustomer
    {
        public int PetID { get; set; }
        public string NameOfPet { get; set; }
        public string BreedType { get; set; }
        public string SizeCategory { get; set; }
        public string Sex { get; set; }
        public string AgeAtFirstVisit { get; set; }
        public string PrimaryPhone { get; set; }
        public string ImportantNotes { get; set; }
        public byte[] Photo { get; set; }
    }
}
